/* eslint-disable @typescript-eslint/no-explicit-any */
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/components/header/header';
import Footer from '@/components/footer/footer';
import { NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';
import MainWrapper from '@/components/mainWrapper/mainWrapper';
import styles from './layout.module.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Troinez',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: any;
}) {
  let messages;
  try {
    messages = (await import(`../../locales/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html className={styles.html} lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Header />
          <MainWrapper content={children} />
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
