FROM --platform=linux/amd64 node:18.12.0-alpine AS builder

WORKDIR /app

COPY . .

RUN npm i --save --legacy-peer-deps
RUN yarn build

FROM --platform=linux/amd64 node:18.12.0-alpine
WORKDIR /usr/src/app
COPY --from=builder /app ./

EXPOSE 3000

RUN ["chmod", "+x", "/usr/src/app/docker-deploy/entrypoint.dev.sh"]

CMD ./docker-deploy/entrypoint.dev.sh
