FROM node:18.12.0-alpine AS builder

WORKDIR /app

COPY . .

RUN npm i --save --legacy-peer-deps
RUN yarn build

FROM node:18.12.0-alpine
WORKDIR /usr/src/app
COPY --from=builder /app ./

EXPOSE 3000

CMD ["yarn", "dev"]
